require:
  - rubocop-rails

Layout/LineLength:
  Enabled: true
  Max: 120
  Include:
    - 'app/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/Documentation:
  Include:
    - app/models/**/*

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/20180208171233_create_incidents.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/incidents_controllers.rb
