require:
  - rubocop-rails

Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120
  Include:
    - 'app/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: normal

Style/Documentation:
  Include:
    - app/models/**/*

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
    - app/helpers/incident_helper.rb
    - app/controllers/incidents_controller.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/20180208171233_create_incidents.rb
    - app/controllers/incidents_controller.rb

Metrics/ClassLength:
  Exclude:
    - app/controllers/incidents_controller.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/helpers/incident_helper.rb
    - app/controllers/incidents_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/incidents_controller.rb
