development:
  adapter: postgresql
  encoding: utf8
  database: backofficer_incident_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: backofficer_incident_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: backofficer_incident_development
  pool: 5
  username:
  password:
